### ISSUE TITLE
When to cut new PATCH version?

### ISSUE THREAD

**Issue by aaronwhite** [rundis/elm-bootstrap#108]
There's a fix for drop down issues ( https://github.com/rundis/elm-bootstrap/commit/d6f22a3a165d8ae1c8e264bd45455bb15d422525 ) that my code-base would absolutely benefit from.

What's the policy/preferred deployment on patch versions of this library? Historically it looks like it's only re-published to the elm repository on more major updates, but I'm curious if I could help enact/encourage/enable more frequent upgrades

Thanks!

**Comment by rundis** [comment]
I could use some more collaborators. If I see more great Pull requests from people I'd be happy to consider adding them as collaborators to the project.

Since I don't get to use Elm at work these days, my time to do maintenance is very limited so I try to batch things to when I have a chunk of time. Last chunk of time of any worth I had was spent on preparing for Elm 0.19.

Anyways. I'll try to see if I have time to cut a release in the not to distant future 😄

**Comment by aaronwhite** [comment]
I'd submit a pull request here, but it'd be a lame "version bump", but I'm happy to ;-)  99.9% the library has been great and not needed modification from us in the form of PRs (we aren't shy) - will certainly submit any when we find 'em
