### ISSUE TITLE
Checkbox only uses strings as a display value

### ISSUE THREAD

**Issue by milogert** [rundis/elm-bootstrap#143]
I noticed that `Bootstrap.Form.Checkbox.checkbox` (and `custom`) only allows a `String` as a display value.

Is it possible to display html there? For instance, if I had a checkbox that was like

- [ ] **Label:** This is a description.

If it's not possible could this be added? Might be nice to have for situations like the above.

**Comment by mordrax** [comment]
I have the same problem. I'd like to do:

![image](https://user-images.githubusercontent.com/4709169/59819501-7b3eae80-936b-11e9-82d4-6116370f6c89.png)

but because the checkbox is a block display, even if I put the bold href after it, it goes to the next line.

What I've done in my UI packages is to make the lbl a `Html msg`, ie:

```
type Checkbox msg
    = Checkbox
        { options : List (Option msg)
       --  , label : String
        , label : Html msg
        }
```

The consequence of this that it will break your API, and the callers won't be as nice:
```
-- currently
checkbox "I Agree to the terms" value msg

-- after
checkbox (Html.text "I agree to the terms") value msg
```

But at least then you can use custom for the latter cases.

In the view, Html.text is simply removed:

```
view =
   ...
    -- [ Html.text chk.label ]
    [ chk.label ]
```

I'm happy to provide a PR if something like this aligns with the goals of the project.
