### ISSUE TITLE
Implement support for Carousel

### ISSUE THREAD

**Issue by mccrodp** [rundis/elm-bootstrap#28]
Hi, thanks for the work on this repo, I'm using it through this repo at the moment : https://github.com/mathieul/brunch-with-elm-bootstrap

I'm trying to simply output a free Boostrap theme using this package's boostrap .elm syntax and believe there maybe no slideshow / carousel element yet. I saw the Accordion, but no carousel.

Is this something on the roadmap or something you would accept via PR?

https://v4-alpha.getbootstrap.com/components/carousel/

**Comment by rundis** [comment]
Yeah haven't gotten around to the carousel thing.
It's going to need to include some state and subscriptions I imagine. Not rocket science but not the simplest addition either.

Pull requests are cool, but it's a good idea to read the readme about rationale and goals for the library. Then if you think this is something you'd like to have a stab at, probably a good idea to startt off with a outline of how the api might look and comment here so that I can evaluate before spending too much time on implementation :-)

If you decide not to, it's tagged and will certainly be considered for implementation for a future release.

**Comment by mccrodp** [comment]
Sounds like a good way to go, @rundis. I think I will postpone for now though as I don't need the slideshow directly, was more for a more complete showcase of outputting a Boostrap theme with Elm. Good to know it's on the roadmap, may revisit if I have time for a challenge. Thanks! 😄

**Comment by rundis** [comment]
@folkertdev Would this be something you'd be interested in taking on ? Maybe more fun that just writing tests ? 😄

**Comment by folkertdev** [comment]
sure

**Comment by rundis** [comment]
Added and released in version 3.0.0.
