### ISSUE TITLE
Card.deck and Card.columns 

### ISSUE THREAD

**Issue by OwenOKI** [rundis/elm-bootstrap#64]
I am unable to size the cards for card.deck, and the sizing for card.columns is odd.

I want to have a deck of of cards, with either 1 column, or 4 columns.  How can this be accomplished?  I found no benefits to setting the Card.config [ Card.attrs [ class "w-100 p-3" ] ]  with card.deck.

I found that card.columns was modified by Card.config [ Card.attrs [ class "w-100 p-3" ] ] , but the modifications were strange.  I was never able to achieve 1, 2 or 4 columns of cards with card.columns.

Overall, I love it, but I wanted a little more control of the card layout with these options.

**Comment by rundis** [comment]
Have you tried to create the effect you wanted with just plain html and the bootstrap 4 css ?
The card stuff is mostly just a thin wrapper over the bootstrap classes, but I might have messed something up somewhere. But if this behavior is the same html without going through elm-bootstrap I guess we'll need to register issues upstream :-)

You may also want to consider using the grid layout (cols and rows) to gain more control over how cards are layed out (rather than Card.columns or Card.deck)

and tx for the feedback !

**Comment by OwenOKI** [comment]
I have things working perfectly by adding the grid / row and some recursion to loop list of items, but I read about the deck and column options, and wanted to try it.

I am not competent enough in HTML / CSS to convert my elm to those options.  I am just a beginner, seeing the value of elm, and building a suite of examples so I can know what I can do.

Owen Ivory
ProWorks
Office: 714-230-2372
Mobile: 714-273-6320
Need ProWorks help?  Register and ask at http://support.proworksinfo.com

**Comment by rundis** [comment]
I'm going to close this issue, it can be reopened if you can provide an example using plain html with bootstrap css that works fine, but doesn't when doing the corresponding thing in elm-bootstrap.
